vim.api.nvim_set_var('gruvbox_contrast_dark', 'medium')
vim.api.nvim_set_var('gruvbox_filetype_hi_groups', 0)
vim.api.nvim_set_var('gruvbox_italicize_strings', 1)
vim.api.nvim_set_var('gruvbox_plugin_hi_groups', 0)
vim.api.nvim_set_var('gruvbox_transp_bg', 0)
